# Generated by Django 3.1.1 on 2020-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200923_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitems',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
