# Generated by Django 3.1.1 on 2020-09-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_otherstatus',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice_otherstatus',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_otherstatus',
            name='invoicedetails',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicedetails'),
            preserve_default=False,
        ),
    ]
